spring.application.name=school-marks-management
server.port=8080

spring.datasource.url=jdbc:h2:mem:schooldb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=dinesh
spring.datasource.password=

spring.jp.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console