spring.application.name=school-marks-management
server.port=8080

#H2 Database
spring.datasource.url=jdbc:h2:mem:schooldb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=dinesh
spring.datasource.password=

spring.jp.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Kafka
spring.kafka.bootstrap-server=localhost:9092
spring.kafka.consumer.group-id=school-marks-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

